### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by davexxx1214** [yihong0618/klingCreator#18]
调用文字生成视频API正常。
但是调用图片生成视频API的时候，会报错： 'NoneType' object has no attribute 'get'
1. https://klingai.kuaishou.com/和https://klingai.com/试了都是同样的错误。
2. 同样的代码以前可以工作，最近发现不行了，不确定是不是官方有什么改动。

**Comment by yihong0618** [comment]
@davexxx1214 可能你 vip 到期了。。。那个是 vip 的功能

**Comment by yihong0618** [comment]
我今天看一下

**Comment by davexxx1214** [comment]
@yihong0618 又测试了一下，感觉像是图片内容审核的问题，虽然不知道是哪里触发审核了。Close了。

**Comment by lschaupp** [comment]
Issue does currently exist
